version: '3.6'

services:
  ospos.mysql.lib.unb.ca:
    build:
      context: .
    command: mysqld --skip-name-resolve --max_allowed_packet=64M
    env_file:
      - ./env/mysql.env
    restart: always
    container_name: ospos.mysql.lib.unb.ca
    expose:
      - "3306"
